language: objective-c
osx_image: xcode7.3

install:
  - carthage bootstrap --platform iOS

script:
  - set -o pipefail
  - xcodebuild build test -scheme zimages-ios -destination 'platform=iOS Simulator,name=iPhone 6s,OS=9.3' | xcpretty -s
